export { default as Main } from './Main/Main'
export { default as BlogPage } from './Blog/BlogPage'
export { default as ProjectPage } from './Project/ProjectPage'
export { default as SkillDiv } from './skilldiv/SkillDiv'
export { default as Volen } from './volen/Volen'